# Use the official Node.js 16 image as a base
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application files    
COPY . .

RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt ./

RUN  pip3 install --no-cache-dir -r requirements.txt

COPY test-googleapi.py ./
RUN python3 test_googleapi.py

# Expose port 4000 to the outside world
EXPOSE 4000

# Command to run the Node.js server
CMD ["node", "server.js"]
